### ISSUE TITLE
Eigen 3.4 support?

### ISSUE THREAD

**Issue by risicle** [norlab-ulaval/libpointmatcher#496]
In the NixOS package for `libpointmatcher` we noticed that building 1.3.1 fails once we upgrade to eigen 3.4.0:

```
/build/source/pointmatcher/DataPointsFilters/Gestalt.cpp:498:52: error: no match for 'operator+=' (operand types are 'Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<float, -1, -1>, float, float> >::type' {aka 'Eigen::IndexedView<Eigen::Matrix<float, -1, -1>, float, float>'} and 'Eigen::DenseCoeffsBase<Eigen::Matrix<float, -1, 1>, 1>::Scalar' {aka 'float'})
  498 |         gestaltMeans(indices(0,it), indices(1,it)) += heights(it);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
```

Full build log available at https://hydra.nixos.org/log/62jmdhygsddz94mdandsg0cni94gv17r-libpointmatcher-1.3.1.drv

It seems that indexed and sliced views had a bit of an overhaul in 3.4 (https://eigen.tuxfamily.org/index.php?title=3.4#New_Major_Features_in_Core) - is it possible this usage wasn't intended to be supported?

**Comment by boxanm** [comment]
The current `develop` branch compiles with Eigen 3.4; we will draft a release soon with these changes. Stay tuned!
